# Generated by Django 5.1.6 on 2025-02-23 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HeatingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReadValues',
            new_name='Info',
        ),
    ]
