# Generated by Django 5.1.6 on 2025-02-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatingApp', '0003_remove_timer_length_info_target_temperature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timer',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='timer',
            name='target_temperature',
            field=models.FloatField(default=21),
        ),
    ]
