# Generated by Django 5.1.6 on 2025-02-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatingApp', '0004_alter_timer_active_alter_timer_target_temperature'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='power',
            field=models.BooleanField(default=True),
        ),
    ]
