# Generated by Django 5.1.6 on 2025-03-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HeatingApp', '0005_info_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
